### ISSUE TITLE
Error while sending event via HttpSender without sharedSecret

### ISSUE THREAD

**Issue by kotofey-da-powah** [p2-inc/keycloak-events#15]
Hi and thanks for your useful extensions!

There is a controversy between readme and actual behaviour of http sender extension. Readme says that sharedSecret field is not required, but when it's not set I catch an unhandled error related to lack of value.

Also this line says that actually this field is not optional:
https://github.com/p2-inc/keycloak-events/blob/ce99d8da9552bf80c6943013ba65f467cb39841d/src/main/java/io/phasetwo/keycloak/events/HttpSenderEventListenerProvider.java#L68

For consistency, I'll propose either fix the readme or fix the code to make this field actually optional.

upd:
Also noticed, that sender started exponential retry despite the fact that "retry" config is unset and default value is "false" according to readme.

**Comment by xgp** [comment]
Hi @kotofey-da-powah thanks for opening this issue. Can you share the unhandled error you're getting?

That method you linked to takes a `sharedSecret` String, but doesn't actually do anything with it unless it's non-null: https://github.com/p2-inc/keycloak-events/blob/main/src/main/java/io/phasetwo/keycloak/events/HttpSenderEventListenerProvider.java#L71

You're right that I need to update the default `retry` to true.

**Comment by kotofey-da-powah** [comment]
There is traceback for unhandled error:
```
2023-04-03 10:14:34,428 WARN  [io.phasetwo.keycloak.events.SenderEventListenerProvider] (pool-3-thread-1) Uncaught Sender error: java.lang.NullPointerException: Cannot invoke "Object.toString()" because the return value of "java.util.Map.get(Object)" is null
2023-04-03T10:14:34.432716199Z 	at io.phasetwo.keycloak.events.HttpSenderEventListenerProvider.getSharedSecret(HttpSenderEventListenerProvider.java:54)
2023-04-03T10:14:34.432773832Z 	at io.phasetwo.keycloak.events.HttpSenderEventListenerProvider.send(HttpSenderEventListenerProvider.java:64)
2023-04-03T10:14:34.432798048Z 	at io.phasetwo.keycloak.events.SenderEventListenerProvider.lambda$schedule$0(SenderEventListenerProvider.java:109)
2023-04-03T10:14:34.432808535Z 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
2023-04-03T10:14:34.432816140Z 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
2023-04-03T10:14:34.432848227Z 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
2023-04-03T10:14:34.432860771Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
2023-04-03T10:14:34.432868504Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
2023-04-03T10:14:34.432875790Z 	at java.base/java.lang.Thread.run(Thread.java:833)
2023-04-03T10:14:34.432880341Z 
2023-04-03T10:14:35.354978044Z 2023-04-03 10:14:35,354 WARN  [io.phasetwo.keycloak.events.SenderEventListenerProvider] (pool-3-thread-1) Uncaught Sender error: java.lang.NullPointerException: Cannot invoke "Object.toString()" because the return value of "java.util.Map.get(Object)" is null
2023-04-03T10:14:35.355163563Z 	at io.phasetwo.keycloak.events.HttpSenderEventListenerProvider.getSharedSecret(HttpSenderEventListenerProvider.java:54)
2023-04-03T10:14:35.355199526Z 	at io.phasetwo.keycloak.events.HttpSenderEventListenerProvider.send(HttpSenderEventListenerProvider.java:64)
2023-04-03T10:14:35.355207283Z 	at io.phasetwo.keycloak.events.SenderEventListenerProvider.lambda$schedule$0(SenderEventListenerProvider.java:109)
2023-04-03T10:14:35.355211892Z 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
2023-04-03T10:14:35.355215770Z 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
2023-04-03T10:14:35.355219686Z 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
2023-04-03T10:14:35.355223745Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
2023-04-03T10:14:35.355227817Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
2023-04-03T10:14:35.355231908Z 	at java.base/java.lang.Thread.run(Thread.java:833)
2023-04-03T10:14:35.355235525Z 
```

Also even if I explicitly set `retry` to false, extension keep sending retry requests anyway. May be this behaviour configuring by another layer?

**Comment by xgp** [comment]
Can you share how you are setting `retry`? I just did a test and I can't get it to retry when set to false.

**Comment by kotofey-da-powah** [comment]
`{"targetUri": "http://host:8000/api/user-log/", "retry": false}`

**Comment by xgp** [comment]
I fixed the secret npe, but wasn't able to reproduce the retry bug with the config you sent. I wrote a test and it seems to work as expected. I added some logging to a branch. Would you mind testing with the [xgp/secret-npe](https://github.com/p2-inc/keycloak-events/tree/xgp/secret-npe) branch? I'm curious what is getting loaded for your config.

**Comment by kotofey-da-powah** [comment]
Sure, i'll test it at my leisure. It's possible that it was my fault during configuration.
