### ISSUE TITLE
java.lang.NoClassDefFoundError: org/keycloak/services/resources/Cors

### ISSUE THREAD

**Issue by ari-party** [p2-inc/keycloak-events#85]
KC 26.0.7
Latest keycloak-events release

GET /auth/realms/master/attributes
```json
{
    "error": "unknown_error",
    "error_description": "For more on this error consult the server log."
}
```

```
ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-3) Uncaught server error: java.lang.NoClassDefFoundError: org/keycloak/services/resources/Cors
	at io.phasetwo.keycloak.resources.CorsResource.setupCors(CorsResource.java:37)
	at io.phasetwo.keycloak.resources.AbstractAdminResource.setupCors(AbstractAdminResource.java:61)
	at io.phasetwo.keycloak.resources.AbstractAdminResource.setup(AbstractAdminResource.java:48)
	at io.phasetwo.keycloak.resources.RealmAttributesResourceProvider.getRealmResource(RealmAttributesResourceProvider.java:14)
	at io.phasetwo.keycloak.resources.BaseRealmResourceProvider.getResource(BaseRealmResourceProvider.java:30)
	at org.keycloak.services.resources.RealmsResource.resolveRealmExtension(RealmsResource.java:269)
	at org.keycloak.services.resources.RealmsResource$quarkusrestinvoker$resolveRealmExtension_c7e400748748bf35309bc60d82a4789f2a0e2d02.invoke(Unknown Source)
	at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:635)
	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.ClassNotFoundException: org.keycloak.services.resources.Cors
	... 18 more```

**Comment by xgp** [comment]
Usually a NoClassDefFoundError means you’re using an incompatible version. Please be more specific about which jar version you’re using and how you are testing.

**Comment by ari-party** [comment]
> Usually a NoClassDefFoundError means you’re using an incompatible version. Please be more specific about which jar version you’re using and how you are testing.

Version 0.28, oops
Chartering new territory with Keycloak.
I'll look into building a Jar from the latest tag.

Sorry!

**Comment by xgp** [comment]
All release jars are in maven central.
